# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f41f9b6d2a49b1b34055092054654bf833ece7c8af307af8e56ddfe3d6de4e196684107e98aa4695dfdc5c6de70f77d1d3e3364c6af36336ec21939b3ac0b8

test:
  secret_key_base: f170eb4c752ca9f8458efe339e5dd66a25e35dcf495b5c5e67fa2a51da933156247c06dca2ef0789d06eda8de96d18a50b688b8a7695f9296b9811964c4c072a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
